### ISSUE TITLE
请教一下，该代码对P/R/F评测指标的计算是实体级别还是tag级别的？

### ISSUE THREAD

**Issue by XSS1144** [Jacen789/sequence-tagging#2]

**Comment by Jacen789** [comment]
实体

**Comment by XSS1144** [comment]
好的，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月11日(星期五) 下午2:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Jacen789/sequence-tagging] 请教一下，该代码对P/R/F评测指标的计算是实体级别还是tag级别的？ (#2)





 
实体
